### ISSUE TITLE
len out of range issue

### ISSUE THREAD

**Issue by omani** [cheggaaa/pb#93]
Hi,

when passing a file size of 15762329 (return of `fi.Size()`) to:
```go
bar = pb.New64(fi.Size()).SetUnits(pb.U_BYTES).SetRefreshRate(time.Millisecond * 10)
```

I get the following panic:
```go
panic: runtime error: makeslice: len out of range

goroutine 15727 [running]:
panic(0x6ee280, 0xc420400250)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
strings.Repeat(0x74b1d0, 0x1, 0xfffffffffffffffd, 0x7, 0xc4203b00a0)
	/usr/local/go/src/strings/strings.go:420 +0x49
github.com/cheggaaa/pb.(*ProgressBar).write(0xc4200ae000, 0x0)
	/home/hasan/gocode/src/github.com/cheggaaa/pb/pb.go:368 +0xa6c
github.com/cheggaaa/pb.(*ProgressBar).Update(0xc4200ae000)
	/home/hasan/gocode/src/github.com/cheggaaa/pb/pb.go:410 +0x5d
github.com/cheggaaa/pb.(*ProgressBar).Start(0xc4200ae000, 0x74db1e)
	/home/hasan/gocode/src/github.com/cheggaaa/pb/pb.go:122 +0x95
gitlab.cloudissh.com/ventilator/go-gridfuse/datastores.(*HTTPDataStore).Write.func1(0xc420100050, 0xc420366380, 0xc42011c040, 0xc4203cc390, 0xc4200ae000, 0xc42011c050, 0xc420400090, 0xc4203062a0)
	/home/hasan/gocode/src/gitlab.cloudissh.com/ventilator/go-gridfuse/datastores/rest-http.go:127 +0x1a5
created by gitlab.cloudissh.com/ventilator/go-gridfuse/datastores.(*HTTPDataStore).Write
	/home/hasan/gocode/src/gitlab.cloudissh.com/ventilator/go-gridfuse/datastores/rest-http.go:134 +0x4e8
make: *** [test] Error 2
```

**Comment by omani** [comment]
the error does not occur when I remove `.SetUnits(pb.U_BYTES).` when initializing `bar`

**Comment by omani** [comment]
it's worth to mention that this only happens when I copy a file with the linux cli command `rsync`.

**Comment by omani** [comment]
this fixes it for me:
```go
if escapeAwareRuneCountInString(out)+2 < width {

		end = strings.Repeat(" ", width-utf8.RuneCountInString(out))
		logrus.Info(end)
	}
```

on line 370 in `pb.go`.

reason for this issue is that between out and width there are two pixels which are not counted in the calculation of out. to recproduce this issue, just make your window 156 pixels in width. or as me in ubuntu snap the window to the right with CTRL + ALT + NUMPAD6 which automatically scales to 156 pixels (on my screen resolution).

**Comment by omani** [comment]
a probably better fix is:

```go
if escapeAwareRuneCountInString(out) < width {
	if width-utf8.RuneCountInString(out) >= 0 {
		end = strings.Repeat(" ", width-utf8.RuneCountInString(out))
	}
}
```

**Comment by omani** [comment]
to complete my previous explanation:
it happens in rsync rather than "cp" in cli because rsync appends an arbitrary extension to the filename like `.yctGIh` before copying it (the application I am using `pb` in is a file transfer app).

so with rsync the filename to copy gets longer (and I also use `bar.Prefix()` so the whole progressbar gets even longer) and somehow there are always 3 pixels missing (can't really explain why because I haven't looked deeper into the code of pb) but it is a good idea anyway to check if an integer is a positive integer before passing it into `strings.Repeat()`.

this issue is fixed for me. a fix in upstream (in whichever way it is done) is appreciated!
